// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm3LmYG9nAJaqcVqUokx2PTHk5TUYCAMM',
    appId: '1:692201536836:web:d40bf5f797227a04902b11',
    messagingSenderId: '692201536836',
    projectId: 'career-pulse-1dd22',
    authDomain: 'career-pulse-1dd22.firebaseapp.com',
    storageBucket: 'career-pulse-1dd22.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFrGKPB_doYJhLyGMz6b9L-aECi1oc8rI',
    appId: '1:692201536836:android:9b22d8deb29f02f6902b11',
    messagingSenderId: '692201536836',
    projectId: 'career-pulse-1dd22',
    storageBucket: 'career-pulse-1dd22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1tDnSLOCP_0iTp6pbep6-JbIOoCSi83A',
    appId: '1:692201536836:ios:3f7fc8ff8e997b26902b11',
    messagingSenderId: '692201536836',
    projectId: 'career-pulse-1dd22',
    storageBucket: 'career-pulse-1dd22.firebasestorage.app',
    androidClientId:
        '692201536836-i36i8tulqnmqvc0844nvi5bfkvjqo9oc.apps.googleusercontent.com',
    iosClientId:
        '692201536836-cja1ol9thftcttjomj8b8l98fng0i9s9.apps.googleusercontent.com',
    iosBundleId: 'com.example.careerPulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1tDnSLOCP_0iTp6pbep6-JbIOoCSi83A',
    appId: '1:692201536836:ios:3f7fc8ff8e997b26902b11',
    messagingSenderId: '692201536836',
    projectId: 'career-pulse-1dd22',
    storageBucket: 'career-pulse-1dd22.firebasestorage.app',
    androidClientId:
        '692201536836-i36i8tulqnmqvc0844nvi5bfkvjqo9oc.apps.googleusercontent.com',
    iosClientId:
        '692201536836-cja1ol9thftcttjomj8b8l98fng0i9s9.apps.googleusercontent.com',
    iosBundleId: 'com.example.careerPulse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBm3LmYG9nAJaqcVqUokx2PTHk5TUYCAMM',
    appId: '1:692201536836:web:d0c94e252ccdd01f902b11',
    messagingSenderId: '692201536836',
    projectId: 'career-pulse-1dd22',
    authDomain: 'career-pulse-1dd22.firebaseapp.com',
    storageBucket: 'career-pulse-1dd22.firebasestorage.app',
  );
}
